import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TextInput,
  TouchableOpacity,
  FlatList,
  KeyboardAvoidingView,
  Platform,
  Alert,
  ScrollView,
} from 'react-native';
import { useTheme } from '@/hooks/use-theme';
import { useLanguage } from '@/hooks/use-language';
import { useAuth } from '@/hooks/useAuth';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { 
  Plus, 
  Trash2, 
  Download, 
  Share2, 
  ChevronLeft,
  CheckCircle2,
  Circle,
  Notebook
} from 'lucide-react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

interface ShoppingItem {
  id: string;
  text: string;
  completed: boolean;
}

export default function ShoppingListScreen() {
  const { colors: theme, isDark } = useTheme();
  const { t } = useLanguage();
  const { user } = useAuth();
  
  const [items, setItems] = useState<ShoppingItem[]>([]);
  const [inputValue, setInputValue] = useState('');

  const storageKey = user ? `shopping_list_${user.id}` : 'shopping_list_guest';

  useEffect(() => {
    loadList();
  }, [user]);

  const loadList = async () => {
    try {
      const saved = await AsyncStorage.getItem(storageKey);
      if (saved) {
        setItems(JSON.parse(saved));
      }
    } catch (e) {
      console.error('Error loading shopping list:', e);
    }
  };

  const saveList = async (newList: ShoppingItem[]) => {
    try {
      setItems(newList);
      await AsyncStorage.setItem(storageKey, JSON.stringify(newList));
    } catch (e) {
      console.error('Error saving shopping list:', e);
    }
  };

  const addItem = () => {
    if (!inputValue.trim()) return;
    const newItem: ShoppingItem = {
      id: Date.now().toString(),
      text: inputValue.trim(),
      completed: false,
    };
    const newList = [newItem, ...items];
    saveList(newList);
    setInputValue('');
  };

  const toggleItem = (id: string) => {
    const newList = items.map(item => 
      item.id === id ? { ...item, completed: !item.completed } : item
    );
    saveList(newList);
  };

  const deleteItem = (id: string) => {
    const newList = items.filter(item => item.id !== id);
    saveList(newList);
  };

  const clearList = () => {
    Alert.alert(
      "Clear All?",
      "Are you sure you want to delete all items from your shopping list?",
      [
        { text: "Cancel", style: "cancel" },
        { text: "Delete All", style: "destructive", onPress: () => saveList([]) }
      ]
    );
  };

  const generatePDF = async () => {
    if (items.length === 0) {
      Alert.alert("List Empty", "Add some ingredients before downloading.");
      return;
    }

    const htmlContent = `
      <html>
        <head>
          <style>
            body { font-family: 'Helvetica'; padding: 40px; color: #333; }
            h1 { color: #8B4513; border-bottom: 2px solid #8B4513; padding-bottom: 10px; }
            .item { font-size: 18px; padding: 10px 0; border-bottom: 1px solid #EEE; display: flex; align-items: center; }
            .completed { color: #888; text-decoration: line-through; }
            .footer { margin-top: 50px; font-size: 12px; color: #AAA; text-align: center; }
          </style>
        </head>
        <body>
          <h1>CookuBuddy Ingredients List</h1>
          <p>Shopping List for: ${user?.email || 'Guest User'}</p>
          <div>
            ${items.map(item => `
              <div class="item ${item.completed ? 'completed' : ''}">
                • ${item.text} ${item.completed ? '(Bought)' : ''}
              </div>
            `).join('')}
          </div>
          <div class="footer">Generated by CookuBuddy App</div>
        </body>
      </html>
    `;

    try {
      const { uri } = await Print.printToFileAsync({ html: htmlContent });
      await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    } catch (e) {
      Alert.alert("Error", "Failed to generate PDF.");
    }
  };

  // Wood/Notepad Design Colors
  const woodDark = '#5D4037';
  const woodLight = '#8D6E63';
  const paperColor = '#FFF9C4'; // Pale yellow like a legal pad
  const lineSecondary = '#B3E5FC'; // Blue horizontal lines
  const linePrimary = '#FFCDD2'; // Red vertical line

  return (
    <View style={[styles.container, { backgroundColor: woodDark }]}>
      {/* WOODEN HEADER */}
      <View style={styles.header}>
        <View style={styles.headerRow}>
          <Notebook size={24} color="#FFF" />
          <Text style={styles.headerTitle}>Ingredients Purchase</Text>
        </View>
        <TouchableOpacity onPress={generatePDF} style={styles.pdfBtn}>
          <Download size={20} color="#FFF" />
          <Text style={styles.pdfBtnText}>PDF</Text>
        </TouchableOpacity>
      </View>

      <KeyboardAvoidingView 
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        style={styles.content}
      >
        <View style={[styles.notepadContainer, { backgroundColor: paperColor }]}>
          {/* Vertical Red Line */}
          <View style={styles.redLine} />
          
          <View style={styles.inputSection}>
            <TextInput
              style={styles.input}
              placeholder="Type ingredient..."
              placeholderTextColor="#999"
              value={inputValue}
              onChangeText={setInputValue}
              onSubmitEditing={addItem}
            />
            <TouchableOpacity onPress={addItem} style={styles.addBtn}>
              <Plus size={24} color={woodDark} />
            </TouchableOpacity>
          </View>

          <FlatList
            data={items}
            keyExtractor={item => item.id}
            renderItem={({ item }) => (
              <View style={styles.listItem}>
                <TouchableOpacity onPress={() => toggleItem(item.id)} style={styles.itemMain}>
                  {item.completed ? (
                    <CheckCircle2 size={22} color="#4CAF50" />
                  ) : (
                    <Circle size={22} color="#AAA" />
                  )}
                  <Text style={[styles.itemText, item.completed && styles.completedText]}>
                    {item.text}
                  </Text>
                </TouchableOpacity>
                <TouchableOpacity onPress={() => deleteItem(item.id)}>
                  <Trash2 size={20} color="#EF5350" />
                </TouchableOpacity>
              </View>
            )}
            contentContainerStyle={styles.listPadding}
            showsVerticalScrollIndicator={false}
            ListEmptyComponent={
              <View style={styles.emptyContainer}>
                <Text style={styles.emptyText}>Your notepad is empty.</Text>
                <Text style={styles.emptySubText}>Add items you need to buy.</Text>
              </View>
            }
          />

          {items.length > 0 && (
            <TouchableOpacity onPress={clearList} style={styles.clearBtn}>
              <Text style={styles.clearBtnText}>Clear All Items</Text>
            </TouchableOpacity>
          )}
        </View>
      </KeyboardAvoidingView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  headerTitle: { fontSize: 20, fontWeight: '800', color: '#FFF' },
  pdfBtn: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    gap: 6, 
    backgroundColor: 'rgba(255,255,255,0.2)', 
    paddingHorizontal: 12, 
    paddingVertical: 8, 
    borderRadius: 12 
  },
  pdfBtnText: { color: '#FFF', fontWeight: '700', fontSize: 12 },
  content: { flex: 1, padding: 16, paddingBottom: 30 },
  notepadContainer: {
    flex: 1,
    borderRadius: 12,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  redLine: {
    position: 'absolute',
    left: 45,
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: '#FFCDD2',
    zIndex: 0,
  },
  inputSection: {
    flexDirection: 'row',
    padding: 20,
    paddingLeft: 60,
    borderBottomWidth: 1,
    borderBottomColor: '#B3E5FC',
    zIndex: 1,
  },
  input: {
    flex: 1,
    fontSize: 18,
    fontWeight: '600',
    color: '#4E342E',
    paddingVertical: 10,
  },
  addBtn: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  listPadding: { paddingLeft: 60, paddingRight: 20, paddingBottom: 100 },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#B3E5FC',
  },
  itemMain: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 15,
  },
  itemText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#4E342E',
  },
  completedText: {
    textDecorationLine: 'line-through',
    color: '#AAA',
  },
  emptyContainer: {
    paddingTop: 100,
    alignItems: 'center',
    opacity: 0.5,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#8D6E63',
  },
  emptySubText: {
    fontSize: 14,
    color: '#8D6E63',
    marginTop: 5,
  },
  clearBtn: {
    position: 'absolute',
    bottom: 20,
    left: 60,
    right: 20,
    height: 44,
    backgroundColor: 'rgba(0,0,0,0.05)',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  clearBtnText: {
    color: '#EF5350',
    fontWeight: '700',
    fontSize: 14,
  },
});
